server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
          native:
            searchLocations: file:///c:/Users/Hernan/git/repository/configurationserver/src/main/resources/config/licensingservice